# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "second" do |second|
        second.vm.box       = "bento/ubuntu-16.04"
        second.vm.hostname  = "second.local"
        second.vm.network "private_network", ip: "192.168.13.37"
        second.vm.synced_folder "../", "/vagrant"
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 512
        vbox.cpus   = 1
    end

    config.vm.provision "shell", path: "Vagrantboot"

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "auto/inventories/dev/hosts"
        ansible.playbook          = "auto/provision.yml"
        ansible.limit             = "all"
    end
end
